Improving install
wells-wood-research/de-stress pull request #150
Opened 2024-05-23 13:52 UTC by MichaelJamesStam

Made DE-STRESS a lot easier to install locally and also to run.

2024-06-10 21:00 UTC, ChrisWellsWood requested changes
Double check the .env file and remove it if it was a mistake. After that, happy to merge.

2024-06-10 21:00 UTC, ChrisWellsWood commented on .env
> +HEADLESS_DESTRESS_WORKERS=3
`.env` should not be in the code base, this one is for testing I think and there is already a file called .env-testing.

2024-06-10 21:00 UTC, ChrisWellsWood commented on run_destress_headless.py
> +
I love this 😃

2024-06-11 11:10 UTC, MichaelJamesStam commented on run_destress_headless.py
> +
This was actually @ESPhoenix 's idea.

2024-06-11 11:11 UTC, MichaelJamesStam commented on .env
> +HEADLESS_DESTRESS_WORKERS=3
This has all been fixed now.

2024-06-11 11:20 UTC, ChrisWellsWood approved these changes
Looks good, merging.

2024-06-11 11:21 UTC, merged